version: '3.8'

networks:
  mineru_net:
    driver: bridge

services:
  # 1. Redis service
  redis:
    image: redis:7-alpine
    container_name: mineru_api_redis 
    networks: 
      - mineru_net
    ports:
      - "6380:6379" 

  # 2. FastAPI Web service
  web:
    build: .
    container_name: mineru_api_web 
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload --reload-dir /app/app
    volumes:
      - ./app:/app/app
      - ./data/input_pdfs:/app/data/input_pdfs
      - ./data/output:/app/data/output
      - ./data/logs:/app/data/logs
    ports:
      - "8001:8000" 
    depends_on:
      - redis
    networks: 
      - mineru_net

  # 3. Celery Worker service
  worker:
    build: .
    container_name: mineru_api_worker 
    command: watchmedo auto-restart --directory=/app/app --pattern=*.py --recursive -- celery -A app.worker.celery_app worker -l info --concurrency=1
    volumes:
      - ./app:/app/app
      - ./data/input_pdfs:/app/data/input_pdfs
      - ./data/output:/app/data/output
      - ./data/logs:/app/data/logs
    depends_on:
      - redis
    networks: 
      - mineru_net